import './globals.css'
import { Inter, Manrope } from 'next/font/google'
import { cx } from '../utils' // <-- this is the new import other option @/utils
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: "--font-in" })

const manrope = Manrope({ subsets: ['latin'], display: 'swap', variable: "--font-mr" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      className={cx(inter.variable, manrope.variable,
        "bg-light dark:bg-dark transition-colors duration-200 ease-in-out font-mr "
      )}
      >
        <Header />
        {children}
      
      </body>
    </html>
  )
}
